In [10]:
import pandas as pd
from IPython.display import display

df = pd.read_csv("data/campeonato-brasileiro-full.csv")
display(df)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9160,9160,38,07/12/2025,16:04,Santos,Cruzeiro,4-2-3-1,4-2-3-1,J. Vojvoda,T. Tite,Santos,"Estádio Urbano Caldeira, Santos",3,0,SP,MG,743978.75
9161,9161,38,07/12/2025,16:04,Sport,Gremio,5-4-1,4-2-3-1,C. de Lucena,L. Castro,Gremio,"Adelmar da Costa Carvalho, Recife",0,4,PE,RS,88755.00
9162,9163,38,07/12/2025,16:04,Botafogo-RJ,Fortaleza,4-2-3-1,4-4-2,Davide Ancelotti,Martin Palermo,Botafogo-RJ,"Estádio Nilton Santos, Rio de Janeiro",4,2,RJ,CE,905640.00
9163,9164,38,07/12/2025,16:04,Atletico-MG,Vasco,4-2-3-1,4-2-3-1,J. Sampaoli,F. Diniz,Atletico-MG,"Arena MRV, Belo Horizonte",5,0,MG,RJ,897255.52
9164,9165,38,07/12/2025,16:04,Internacional,Bragantino,4-4-2,4-2-3-1,R. Díaz,V. Mancini,Internacional,"Estádio Beira-Rio, Porto Alegre",3,1,RS,SP,1111157.00

In [14]:
# converter campo data da base para o formato datetime
df["data"] = pd.to_datetime(df["data"], format="%d/%m/%Y")

df2025 = df[df["data"].dt.year == 2025]
display(df2025)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
8785,8786,1,2025-03-29,18:30,Juventude,Vitoria,4-2-3-1,4-2-3-1,M. Barbieri,J. Ventura,Juventude,"Alfredo Jaconi, Caxias do Sul",2,0,RS,BA,220000.00
8786,8787,1,2025-03-29,18:30,Fortaleza,Fluminense,3-4-3,4-3-3,T. Carpini,L. Luis Zubeldia,Fortaleza,"Arena Castelão, Fortaleza",2,0,CE,RJ,267643.00
8787,8790,1,2025-03-29,18:31,Cruzeiro,Mirassol,4-2-2-2,4-2-3-1,T. Tite,R. Guanaes,Cruzeiro,"Mineirão, Belo Horizonte",2,1,MG,SP,2089452.00
8788,8788,1,2025-03-29,18:32,Gremio,Atletico-MG,4-2-3-1,4-4-2,L. Castro,J. Sampaoli,Gremio,"Arena do Grêmio, Porto Alegre",2,1,RS,MG,1175509.00
8789,8789,1,2025-03-29,18:32,Sao Paulo,Sport,3-4-1-2,4-3-1-2,H. Crespo,C. de Lucena,-,"MorumBIS, São Paulo",0,0,SP,PE,2144747.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9160,9160,38,2025-12-07,16:04,Santos,Cruzeiro,4-2-3-1,4-2-3-1,J. Vojvoda,T. Tite,Santos,"Estádio Urbano Caldeira, Santos",3,0,SP,MG,743978.75
9161,9161,38,2025-12-07,16:04,Sport,Gremio,5-4-1,4-2-3-1,C. de Lucena,L. Castro,Gremio,"Adelmar da Costa Carvalho, Recife",0,4,PE,RS,88755.00
9162,9163,38,2025-12-07,16:04,Botafogo-RJ,Fortaleza,4-2-3-1,4-4-2,Davide Ancelotti,Martin Palermo,Botafogo-RJ,"Estádio Nilton Santos, Rio de Janeiro",4,2,RJ,CE,905640.00
9163,9164,38,2025-12-07,16:04,Atletico-MG,Vasco,4-2-3-1,4-2-3-1,J. Sampaoli,F. Diniz,Atletico-MG,"Arena MRV, Belo Horizonte",5,0,MG,RJ,897255.52
9164,9165,38,2025-12-07,16:04,Internacional,Bragantino,4-4-2,4-2-3-1,R. Díaz,V. Mancini,Internacional,"Estádio Beira-Rio, Porto Alegre",3,1,RS,SP,1111157.00